language: elixir
elixir: 1.8.1
addons:
  postgresql: '9.4'
services:
- postgresql
env:
  global:
  - MIX_ENV=test
before_script:
- cp config/travis.exs config/test.exs
- mix do ecto.create, ecto.migrate
script:
- mix compile
deploy:
  provider: heroku
  api_key:
    secure: uLVh2RTvRBOcMpQ2WLS4u9EoiaaB1VpxUgbGLQ190R7CPufTbaO9Zh6TmAxkElVsvRUuwdD4huNdwzamI6Dy4CjikRM3kLxt4hLcsRe7RTzMQAYDfabw0VYy2Ysa11ZfN5O+voN3C1vAIsGWIeU9FhxDOmnsxgpj9Bi5ZMjabGQEd1ld7J2jAhABXDgxq3mhVGSbxLHdG7r2udzw/w8PP6dRBid8x8wbg6UpuhUcIjdSK9JZY6RVpPk1V9B7zB517QLbHhlAoZ9k8Qd43uWHYWxUs89yAmczKG4IHZndHSlSTggZpP4A8H0eWLfusL0OZV9AzAWw5GMOLHvvLI39FPSyqOS8KFnaBATKl0tuRsDi8iZ8x0iGgt7qSJTx9Ebj/IjJyP9z2dvaRDhkQyGSdxg5gAz5tvb7tvaDWVvV/vNhMgQ2im5QhOMNdh7VpsxIzApiMLYbylQkRUXK72mbaeHXVWGh/Y4EJt2egiOL7ZqnkA/tcDEBfh+IyW1y7rsV51GYEWVMwR0jtPN+8Bfc93fZl7duDsNark2oUSdiv5zKjUpUmzgR812nqciS1A5FTADvv5TBAIeoTVPAtg5ThpVJcUDjT1G1pV461kS2LVMpDJRIuXXW6bV9y8XDM+o9KVdsUa5AoKCRMAb6FfWawERwAq3goXZewNJueAorJx8=
  app:
    master: inochut
