language: elixir
elixir: 1.8.1
addons:
  postgresql: '9.4'
services:
- postgresql
env:
  global:
  - MIX_ENV=test
before_script:
- cp config/travis.exs config/test.exs
- mix do ecto.create, ecto.migrate
script:
- mix compile
deploy:
  provider: heroku
  api_key:
    secure: BHiiO/7hQyLEGasLcml9JevK01IuYVgIUR5LbA6qmvixvNjjXgjZ8ADQwCs0X9FWfpyt5qUwszdcM3BTy5uqNZ7Tqn2EOMT03r2Tm+9YlD5mpj8L0JzPvNHhcJKxsQgVltTb70xah/JdoWlNbxACvjmzbMhEiZbKC2dHOiMDm9B4xXNDdwLonhJK1emIXf8AEjRKMOVarLqLwWcKGdLSN0vyWKPRNMZx2W2Uk4ykQYZyCXX3PbjFD9J9zvMP41iDhwPUaAw/nKJrREgLnDHjF6HO1Xx95TQLBB/nYFI2MNLw4w072g7+YJbr06RWqewnwIsz29HIQ+yaD76kSUp2lM++DQk1qqjybbIRCC3hXqql9+HxKK/Q3RS3Q/KQTZeRdx/B2miSJvHvoRiGju8+ISCAv72fu1j/EdwoEN1WOrXE/DzxBzwUEK64fTw1kZe26DQeZuW4jhszmK6w4YeWjTiufpD1JU3oGpy5xULMknSnYooAWHTKOK79nm/uaPEQ21Ftm05JEAvvIAJF28QagCLFiYJByTzJJjJxibzRMq8s6JyPPSCB1NT/cVget4sSPa6gPAiIXcDWEICWd3siRqwSe7cdzXtHf+QduBtslG2DZIG5BA+1s0uLTYv6Z27MbhtoTXY63C/oOZ5b7YumXBw73Gr6WHvoDazRCgMFxZE=
  app:
    master: inochut
