language: elixir
elixir: '1.4.4'

addons:
  postgresql: '9.4'

services:
  - postgresql

env:
 global:
  - MIX_ENV=test

before_script:
  - cp config/travis.exs config/test.exs
  - mix do ecto.create, ecto.migrate

script:
  - mix compile

deploy:
  provider: heroku
  api_key:
    secure: pd7WYuQfaysIU8T4gI63Lkxs8Nd5GpEqUWKL/ljASeFh/Q0h9Ekyzw79P5RRc08IFfOEO7WHARV3DmgkbgBpxEoSeD1si1NPE9EobjixJPNpmTneDTGmIPwy1IZbnOdl8CqOypVkDtjwEm6RWjsUZQn4ZknCtl+PhfE6wx2H25OVAXd+6/YJPHPNiYSE/IvJtloFWz3kmXuGhqyH5W7PbfBnteTgMC8gVKaMmc5VApcnY3c7PDyz+ZJbZ939jWtNSYHdquwVoWDrrktdV9vIBfqyQZt+6VTtv+sHRXn5CfeeIzkXxobOyrA6cCLB+bAw+jyGBVPUqbBhYXZTvsiKjELzY5unvSXs9J5ypw0kcpe3Bi9hIJqKFWDiqyY9SRc20DKnfTlXnTyn6XYMgrL7iWQLto7qRrfiWUE3kDIO39eGZC9p/Fz4kiYCVjqTO4y+AmGlB0n58mbnJHNfuW3eXerd4MPURUOfGlrhn09OIxO1O8MkY5Mk3mAfv087VtQ6JtxtKt8WGUDdXSywnDxBbWDUxbkRG1uDnoVjvpdAJcS2e0EUbVtzdg7MYiKkqwf8EVJapOEB3EYsblFY0QkWwqC8k1FsrCuyiHN6rKOFrn/1EbVWt6L+89cz+0+jn/FqmVNTrsuhrbN0d99pQLizdv14XpiyZmqLnGG5Sg/omsE=
  app: inochut
