version: '2'
services:
  web:
    build: .
    command: mix phoenix.server
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    depends_on:
      - db

  db: 
    image: postgres:9.3
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
