version: '3'
services:
  web:
    build: .
    command: mix phoenix.server
    environment:
      - HOST_URL=http://localhost:4000 
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    depends_on:
      - db

  analyse:
    build: 
      context: .
      dockerfile: Dockerfile.analyse
    volumes:
      - ./web/elm:/app
    command: elm-analyse -s
    ports:
      - "3000:3000"

  db: 
    image: postgres:9.5
    ports:
      - "5432:5432"
    volumes:
      - .:/app

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
